version: '3'
services:
  web:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev"

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run start"
