version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - arthas
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123456
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb-container:27017/aroundb
    depends_on:
      - mongodb
    networks:
      - arthas
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

      
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      - DATABASE_URL=mongodb://mongodb-container:27017/aroundb
      - JWT_SECRET=Othmar_Garithos
      - NODE_ENV=production
    volumes:
      - ./backend:/usr/src/app
    networks:
      - arthas
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
      
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - http://backend:3001
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - arthas
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
      
networks:
  arthas:
    driver: bridge

volumes:
  mongodb-data:
